package com.forum_hub.api.domain.course;

public enum Category {
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_SCIENCE,
    ARTIFICIAL_INTELLIGENCE,
    MACHINE_LEARNING,
    CLOUD_COMPUTING,
    DEVOPS,
    DATABASE_MANAGEMENT,
    GAME_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    CYBER_SECURITY,
    BLOCKCHAIN,
    INTERNET_OF_THINGS,
    EMBEDDED_SYSTEMS,
    NETWORKING,
    AUGMENTED_REALITY,
    VIRTUAL_REALITY,
    BIG_DATA,
    QUANTUM_COMPUTING,
    UX_UI_DESIGN
}
